### ISSUE TITLE
gtk-doc file names conflict with gtk-layer-shell

### ISSUE THREAD

**Issue by ainola** [wmww/gtk4-layer-shell#13]
If there's going to be a separate repository for the gtk4 variant, then it would be nice if both gtk-layer-shell and gtk4-layer-shell could co-exist. Presently, the following files conflict:

* /usr/share/gtk-doc/html/gtk-layer-shell/api-index-full.html
* /usr/share/gtk-doc/html/gtk-layer-shell/gtk-layer-shell.devhelp2
* /usr/share/gtk-doc/html/gtk-layer-shell/home.png
* /usr/share/gtk-doc/html/gtk-layer-shell/index.html
* /usr/share/gtk-doc/html/gtk-layer-shell/left-insensitive.png
* /usr/share/gtk-doc/html/gtk-layer-shell/left.png
* /usr/share/gtk-doc/html/gtk-layer-shell/right-insensitive.png
* /usr/share/gtk-doc/html/gtk-layer-shell/right.png
* /usr/share/gtk-doc/html/gtk-layer-shell/style.css
* /usr/share/gtk-doc/html/gtk-layer-shell/up-insensitive.png
* /usr/share/gtk-doc/html/gtk-layer-shell/up.png

**Comment by SilverRainZ** [comment]
Hi @wmww, I am making an archlinux package (AUR) for gtk4-layer-shell. I hope we can have a new release so it can be installed together with gtk-layer-shell.

**Comment by SilverRainZ** [comment]
FYI: https://aur.archlinux.org/packages/gtk4-layer-shell

**Comment by wmww** [comment]
I'll do that, but it will likely be a week or two as I'm busy with a work event next week.

**Comment by ainola** [comment]
No problem! Thanks for looking at it. Have a good event :)

**Comment by SilverRainZ** [comment]
ping~ can we get a release recently? :D

**Comment by wmww** [comment]
Done
