### ISSUE TITLE
Not building on arch

### ISSUE THREAD

**Issue by charklie** [wmww/gtk4-layer-shell#36]
[meson-log.txt](https://github.com/wmww/gtk4-layer-shell/files/14578828/meson-log.txt)
[testlog.txt](https://github.com/wmww/gtk4-layer-shell/files/14578829/testlog.txt)

I tried downloading from source, from aur and from cargo but all exit with code 4 and fail on test 14/33 integration-test-menu-popup.

**Comment by abenz1267** [comment]
Change your theme to something default. Like adwaita or raleigh. Then build. then change back to whatever you used before.

**Comment by charklie** [comment]
> Change your theme to something default. Like adwaita or raleigh. Then build. then change back to whatever you used before.

Sorry for the late reply but this didn't work, and so didn't it build when downloading from the tty.

**Comment by abenz1267** [comment]
just tried installing on a fresh install, doesn't work indeed. not even when changing the theme.

**Comment by gmankab** [comment]
```log
Traceback (most recent call last):
  File "/usr/bin/g-ir-scanner", line 103, in <module>
    from giscanner.scannermain import scanner_main
  File "/usr/lib/gobject-introspection/giscanner/scannermain.py", line 35, in <module>
    from giscanner.ast import Include, Namespace
  File "/usr/lib/gobject-introspection/giscanner/ast.py", line 27, in <module>
    from .sourcescanner import CTYPE_TYPEDEF, CSYMBOL_TYPE_TYPEDEF
  File "/usr/lib/gobject-introspection/giscanner/sourcescanner.py", line 31, in <module>
    from giscanner._giscanner import SourceScanner as CSourceScanner
ModuleNotFoundError: No module named 'giscanner._giscanner'
[107/134] Linking target test/test-set-anchor-normalizes-booleans
ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: gtk4-layer-shell-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
gtk4-layer-shell - exit status 4
```

**Comment by simonm** [comment]
Same problem here. Any suggestions on how to get it to pass tests?  Let me know how I can help to troubleshoot this and find a solution!
