### ISSUE TITLE
Arch users: extra meson attribute is needed

### ISSUE THREAD

**Issue by kooskaspers** [wmww/gtk4-layer-shell#40]
The `--prefix=/usr` command-line flag must always be passed to meson setup because Arch Linux packages must not install files to /usr/local. For me this was the reason I couldn't compile and install it from source.

For arch users, the following should work:

```
meson setup --wipe --prefix=/usr -Dexamples=true -Ddocs=true -Dtests=true build
ninja -C build
sudo ninja -C build install
sudo ldconfig
```
Now test with:
```
gtk4-layer-demo
```

Now you should be lucky.

**Comment by zefr0x** [comment]
In arch you should use `arch-meson`, not `meson`.

just carefully read the wiki before writing any package for arch

**Comment by wmww** [comment]
This doesn't seem to be an issue with this library in particular, just a general Arch/meson thing. That being said people seem to keep running into it, so I added a note to the readme 5e49dc98afe327c09644ca8467792bab6455fd10
